### ISSUE TITLE
Admin Bypass Permission [Suggestion]

### ISSUE THREAD

**Issue by KhaozFrost** [Flashback083/Safari#3]
Admin Bypass Permission where timer doesn't get applied to people with said permissions. Broadcasts don't appear for said person/etc.
(When I'm working on the server it can be a pain in the butt to be kicked and lose the last worldedit clipboards)

**Comment by Flashback083** [comment]
Add in last PR

**Comment by KhaozFrost** [comment]
bypass doesnt work. it doesnt display the time or anything but when the timer is up it will still kick,
25.05 02:02:17 [Server] Server thread/INFO FrostEffects was kicked by Server. 25.05 02:02:17 [Server] Server thread/INFO Reason: [Safari] Your time within the Safari has ended; you have been transferred to the hub. 25.05 02:02:17 [Disconnect] User FrostEffects has disconnected, reason: [Safari] Your time within the Safari has ended; you have been transferred to the hub. 25.05 02:02:17 [Server] Server thread/INFO [-] [Founder] FrostEffects has left the server.

**Comment by Flashback083** [comment]
Be carefull, even if you have the * permission, you need to add the bypass permission do you add it?

**Comment by KhaozFrost** [comment]
I dont use * lol. Ras would kill me. Only using the perm itself.

**Comment by Flashback083** [comment]
Weird its work for me 🤔 Maybe the version of LP ? Try to use the latest, if isnt work, i'll make some research

**Comment by Flashback083** [comment]
Fix in 2.3.3
